version: '3.1'
services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_USER=${DATABASE_USERNAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_DB=${DATABASE}'
    volumes:
      - 'data:/var/lib/postgresql/data'
    ports:
      - '${DATABASE_PORT}:5432'
volumes:
  data: {}
